[target.x86_64-pc-windows-msvc]
# rust-lld won't work with dynamic on Win11 :(
# linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=n"]

# RasPi4
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

# Optimization
[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
